// Re-export database types (generated by Supabase CLI)
export type { Database } from './database.types'

// Shared constants
export const SLOT_TYPES = ['daily', 'weekly'] as const
export type SlotType = (typeof SLOT_TYPES)[number]

export const CREATIVE_STATUS = ['draft', 'submitted', 'approved', 'rejected', 'disabled'] as const
export type CreativeStatus = (typeof CREATIVE_STATUS)[number]

export const CAMPAIGN_STATUS = ['scheduled', 'active', 'completed', 'paused', 'canceled'] as const
export type CampaignStatus = (typeof CAMPAIGN_STATUS)[number]

export const DESTINATION_TYPES = ['url', 'universal_link', 'deep_link'] as const
export type DestinationType = (typeof DESTINATION_TYPES)[number]
